Brings in Terraform lock file
This was created with `terraform init`.

When I ran `terraform plan` before doing init, I got the error:

    Error: Inconsistent dependency lock file

    The following dependency selections recorded in the lock file are
    inconsistent with the current configuration:
      - provider registry.terraform.io/hashicorp/aws: required by this
        configuration but no version is selected

    To make the initial dependency selections that will initialize the
    dependency lock file, run: `terraform init`